### ISSUE TITLE
Update to recent JSR versions

### ISSUE THREAD

**Issue by keilw** [unitsofmeasurement/heart-of-glass#1]
Create a new release, at least based on 0.8 RC3 of JSR 363

**Comment by garretwilson** [comment]
Sorry to leave an off-topic comment, but any idea how I can keep from getting notifications for every single repository created in this project? It seems to add me as a watcher whenever a new repository is created.

**Comment by keilw** [comment]
There's an Unsubscribe button, did you try that?

**Comment by garretwilson** [comment]
I'm not subscribed.

The problem is that I'm added as a _watcher_ for each new repository that's added in this project.

I can unwatch this repository, but it will re-add me for new repositories for the organization.

See the [discussion on Stack Overflow](https://stackoverflow.com/q/25108169). It looks like this just can't be done unless I turn off auto-watch for all the organizations. I guess I'll have to do that.

**Comment by keilw** [comment]
You are because you are member of the @unitsofmeasurement/contributors team. There is a sidebar "Notifications" with an "Unsubscribe" button, that way it should be possible to silence notifications for any repository you're not interested in. There is "Subscribed" (seems the default at least for the 21 repos of Contributors) "Unsubscribed" and "Custom" then you'd only be notified when someone mentions you in a discussion by name.

**Comment by keilw** [comment]
If that doesn't work you may be able to remove yourself from the Contributors team, I haven't tried it, but I would only remove someone unless they insist on it or violate a code of conduct, etc.
